version: '3.4'
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "1Secure*Password1"
      ACCEPT_EULA: "Y"

  cinemaservice-api:
    build: .
    ports:
      - "8080:80"